<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageSeeder extends Seeder
{
    public $pages = [
        [   'parent_id' => 0,
            'slug' => 'home',
            'title_en' => 'Home',
            'title_tr' => 'Ana sayfa',
            'title_ru' => 'Главная',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'Water and Waste Water Treatment and Reuse',
            'description_tr' => 'Su / Atık Su Sistemlerinde Arıtma, Şartlandırma ve Geri Kazanım',
            'description_ru' => 'Очистка, кондиционирование и восстановление в системах водоснабжения и канализации',
        ],
        [   'parent_id' => 0,
            'slug' => 'about',
            'title_en' => 'About us',
            'title_tr' => 'Hakkimizda',
            'title_ru' => 'О компании',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'We help our customers to reduce their costs related to water & energy & maintenance',
            'description_tr' => 'Müşterilerimize su, enerji, bakım ile ilgili maliyetleri azaltmalarında yardımcı oluyoruz',
            'description_ru' => 'Помогаем нашим клиентам снижать затраты, связанные с водой, энергетикой, техническим обслуживанием',
        ],
        [   'parent_id' => 0,
            'slug' => 'services',
            'title_en' => 'Services',
            'title_tr' => 'Hi̇zmetleri̇mi̇z',
            'title_ru' => 'Услуги',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'Cleaning, conditioning and restoration services in water supply and sewerage systems',
            'description_tr' => 'Su temini ve kanalizasyon sistemlerinde temizlik, şartlandırma ve restorasyon hizmetleri',
            'description_ru' => 'Услуги по чистке, кондиционированию и восстановлению в системах водоснабжения и канализации',
        ],
        [   'parent_id' => 0,
            'slug' => 'applications',
            'title_en' => 'Applications',
            'title_tr' => 'Uygulamalar',
            'title_ru' => 'Технологии',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'Modern technologies for water purification and reuse, extraction of useful substances from wastewater',
            'description_tr' => 'Su arıtma ve yeniden kullanım için modern teknolojiler, atık sudan faydalı maddelerin çıkarılması',
            'description_ru' => 'Современные технологии очистки и переиспользования воды, извлечение из стоков полезных веществ',
        ], 
        [   'parent_id' => 0,
            'slug' => 'posts',
            'title_en' => 'News',
            'title_tr' => 'Haberler',
            'title_ru' => 'Новости',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'News and announcements from OrgaKimya',
            'description_tr' => 'OrgaKimya\'dan haberler ve duyurular',
            'description_ru' => 'Новости и объявления компании OrgaKimya',
        ],
        [   'parent_id' => 0,
            'slug' => 'articles',
            'title_en' => 'Libraru',
            'title_tr' => 'Bi̇lgi̇ Bankasi',
            'title_ru' => 'Статьи',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'Collection of articles about purification and reuse of water',
            'description_tr' => 'Suyun arıtılması ve yeniden kullanılması ile ilgili makalelerin toplanması',
            'description_ru' => 'Сборник статей про очистку и переиспользование воды',
        ],
        [   'parent_id' => 0,
            'slug' => 'contacts',
            'title_en' => 'Contacts',
            'title_tr' => 'İleti̇şi̇m',
            'title_ru' => 'Контакты',
            'promo_en' => '',
            'promo_tr' => '',
            'promo_ru' => '',
            'content_en' => '',
            'content_tr' => '',
            'content_ru' => '',
            'route_en' => '',
            'route_tr' => '',
            'route_ru' => '',
            'description_en' => 'We are located in Istanbul, Maltepe district',
            'description_tr' => 'İstanbul Maltepe semtindeyiz',
            'description_ru' => 'Мы находимся в г. Стамбул, район Maltepe',
        ],
        // [   'parent_id' => 0,
        //     'slug' => '',
        //     'title_en' => '',
        //     'title_tr' => '',
        //     'title_ru' => '',
        //     'promo_en' => '',
        //     'promo_tr' => '',
        //     'promo_ru' => '',
        //     'content_en' => '',
        //     'content_tr' => '',
        //     'content_ru' => '',
        //     'route_en' => '',
        //     'route_tr' => '',
        //     'route_ru' => '',
        //     'description_en' => '',
        //     'description_tr' => '',
        //     'description_ru' => '',
        // ],

    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->pages as $page) {
            DB::table('pages')->insert($page);
        }
    }
}
